import { FormEvent, useState } from "react";
import { ArrowRight, BookOpen, CheckCircle2, Eye, EyeOff, ShieldCheck } from "lucide-react";
import { api } from "../services/api";
import type { Role, User } from "../types";
export function AuthPage({ mode, onMode, onAuthenticated }: { mode: "login" | "signup"; onMode: (value: "login" | "signup") => void; onAuthenticated: (user: User) => void }) {
 const [loading, setLoading] = useState(false), [error, setError] = useState(""), [show, setShow] = useState(false); const [form, setForm] = useState({ name: "", email: "", password: "", confirm: "", role: "student" as Role });
 const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (mode === "signup" && form.password !== form.confirm) return setError("Passwords do not match."); setLoading(true); try { if (mode === "login") onAuthenticated((await api.login(form.email, form.password)).user); else { await api.signup({ full_name: form.name, email: form.email, password: form.password, confirm_password: form.confirm, role: form.role }); onMode("login"); setError("Account created. You can now sign in."); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to continue."); } finally { setLoading(false); } };
 const set = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: value });
 return <div className="auth-layout"><section className="auth-aside"><div className="auth-brand"><div className="brand-mark"><BookOpen size={20}/></div><b>Adaptive Enterprise RAG</b></div><div><span className="eyebrow">ENTERPRISE KNOWLEDGE INTELLIGENCE</span><h1>Answers grounded in the knowledge your teams trust.</h1><p>Adaptive retrieval determines the right depth of evidence before an answer is generated.</p></div><div className="auth-benefits"><span><CheckCircle2/> Adaptive evidence depth</span><span><CheckCircle2/> Source-aware answers</span><span><CheckCircle2/> Secure session access</span></div></section><main className="auth-card-wrap"><form className="auth-card" onSubmit={submit}><div><span className="eyebrow">{mode === "login" ? "WELCOME BACK" : "CREATE WORKSPACE ACCESS"}</span><h2>{mode === "login" ? "Sign in to your workspace" : "Create your account"}</h2><p>{mode === "login" ? "Access your enterprise knowledge assistant." : "Choose the access role that matches your position."}</p></div>{mode === "signup" && <label>Full name<input required value={form.name} onChange={e => set("name", e.target.value)} placeholder="Your full name"/></label>}<label>Email<input required type="email" autoComplete="username" value={form.email} onChange={e => set("email", e.target.value)} placeholder="name@company.com"/></label><label>Password<div className="password-input"><input required minLength={1} type={show ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} value={form.password} onChange={e => set("password", e.target.value)} placeholder="Enter your password"/><button type="button" onClick={() => setShow(!show)} aria-label="Toggle password visibility">{show ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></label>{mode === "signup" && <><label>Confirm password<input required type="password" autoComplete="new-password" value={form.confirm} onChange={e => set("confirm", e.target.value)} placeholder="Re-enter your password"/></label><label>
  Role
  <select
    value={form.role}
    onChange={e => set("role", e.target.value)}
  >
    <option value="student">Student</option>
    <option value="teacher">Teacher</option>
    <option value="office">Office</option>
    <option value="admin">Admin</option>
  </select>
</label></>}{error && <div className={error.startsWith("Account created") ? "form-success" : "form-error"}>{error}</div>}<button className="primary-button" disabled={loading}>{loading ? (mode === "login" ? "Signing in…" : "Creating account…") : <>{mode === "login" ? "Sign in" : "Create account"}<ArrowRight size={18}/></>}</button><p className="switch-auth">{mode === "login" ? "New to the workspace?" : "Already have an account?"} <button type="button" onClick={() => { setError(""); onMode(mode === "login" ? "signup" : "login"); }}>{mode === "login" ? "Create an account" : "Sign in"}</button></p><div className="session-note"><ShieldCheck size={15}/> Secure, cookie-based session authentication</div></form></main></div>;
}
